### ISSUE TITLE
Resize tutorial gif 

### ISSUE THREAD

**Issue by RajivSah** [RajivSah/make-runner#12]
Reduce the height of the tutorial gif in the readme file so that it can fit on the screen.

**Comment by Shweta200126** [comment]
@RajivSah  I would like to work on this.

**Comment by RajivSah** [comment]
@Shweta200126 Please go ahead.

**Comment by Shweta200126** [comment]
@RajivSah 
Hey I did try a lot but couldnt do it coz the first one wont happen to resize but if u do this
1: img src="sample. gif" height=1000  width=1000 align="center" another one gets form and is resized. 
But I did try with making 2: ![](sample.gif) a comment and it doesnt vanishes and  
1: also appears . 

If I dont use 2: then 1: wont appear. 

Ur help will be appreciated , I dont know much of css. I hope I could help.

**Comment by RajivSah** [comment]
@Shweta200126 Thanks for the effort that you have made.
Can you create a PR of what you have tried? I would be able to understand your problem better that way.

**Comment by Shweta200126** [comment]
@RajivSah yup ofcourse !

**Comment by RajivSah** [comment]
@Shweta200126 Could you open PR in this repo itself instead of your forked repo?

**Comment by Shweta200126** [comment]
@RajivSah  doing it. 

I read its suggested to fork it and then make a pull - request . 
Did I do something wrong?
