### ISSUE TITLE
Add extension logo

### ISSUE THREAD

**Issue by RajivSah** [RajivSah/make-runner#5]
Currently, the extension is published without any logo. This issue is to add a logo for the extension.
Logo sample:
<img width="64" alt="Screen Shot 2020-10-13 at 09 27 21" src="https://user-images.githubusercontent.com/25024214/95815453-69410600-0d3c-11eb-9d13-486f76775eb5.png">

**Comment by anacarolinaarellano** [comment]
Can you assign me this issue?

**Comment by RajivSah** [comment]
> Can you assign me this issue?

Sorry, This issue is already taken.
